[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/roadmap/capstone-projects"
  to = "/roadmap/interview-projects"
  status = 301

[[redirects]]
  from = "/roadmap/capstone-projects/*"
  to = "/roadmap/interview-projects/:splat"
  status = 301
